name: easygymclub
description: Tu nueva forma de entrenar.


# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  generic_bloc_provider: ^1.0.9
  cupertino_icons: ^0.1.2
  image_picker: ^0.5.4+3
  shared_preferences: ^0.5.6
  rxdart: ^0.23.1
  connectivity: ^0.4.8+2
  decimal: ^0.3.5
  dio: ^3.0.9
  # Dependencie for Agenda screen
  flutter_calendar_carousel: ^1.4.10
  sqflite: ^1.2.0
  # Permissions
  permission_handler: ^5.0.0+hotfix.3
  http: ^0.12.0+4
  # Dependencie for Entrada al gym screen
  qr_flutter: ^3.1.0
  # Dependencies for Rutina screen
  countdown_flutter: ^0.1.1
  soundpool: ^0.6.1
  # Probando music player
  spotify_sdk: ^0.3.2
  # Dependencies to use spotify_sdk
  logger: ^0.8.3
  json_annotation: ^3.0.1
  # Animation dependencie for Musica player
  avatar_glow: ^1.1.0
  # Loader Button
  rounded_loading_button: ^1.0.0
  # Dependencies for Google maps
  location: ^2.5.2
  google_maps_flutter: ^0.5.24+1
  flutter_plugin_android_lifecycle: ^1.0.6
  flutter_polyline_points: ^0.1.0
  # Make a foreground service to keep the app alive on background
  
  background_fetch: '^0.5.1'
  background_locator: ^1.1.3+1
  # Timer
  stop_watch_timer: ^0.2.0+2
  # Notificaciones
  #onesignal_flutter: ^2.0.0
  # Icons
  font_awesome_flutter: ^8.8.1
  # Youtube player
  youtube_player_flutter: ^6.1.0+4
  # Screen loader
  argon_buttons_flutter: ^1.0.2
  loading_overlay: ^0.2.1
  animated_text_kit: ^2.0.0
  provider: ^4.0.4
  # Url
  url_launcher: ^3.0.3
  # Transparent image
  transparent_image: ^1.0.0
  # Modal
  awesome_dialog: ^0.1.3
  # Cuenta pasos
  pedometer: ^1.0.0
  # Date picker
  flutter_cupertino_date_picker: ^1.0.24
  # Bottom Modal
  modal_bottom_sheet: ^0.1.5
  flutter_circular_chart: ^0.1.0
  path_provider: ^1.6.9
  numberpicker: ^1.2.0
  fluttertoast: ^4.0.0
  location_permissions: ^2.0.5
  flutter_local_notifications: ^1.4.4+1 
  better_player: ^0.0.8
  firebase_messaging: ^6.0.16
  # Calcular edad en base a la fecha
  age: ^0.0.1
  locally: ^0.2.6+9
  shimmer: ^1.1.1
  loadmore: ^1.0.4
  get: ^3.13.0
  manage_calendar_events: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.3
  test: ^1.9.4
  mockito: ^4.1.1
  flutter_launcher_name: "^0.0.1"

flutter_launcher_name:
  name: "Easy Gym Club" 
  

flutter_icons:
  image_path: "assets/img/logo1.png"
  android: true
  ios: true
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  assets:
    # Images
    - assets/img/logo1.png
    - assets/img/bgr.png
    - assets/img/logo.svg
    - assets/img/logo2.png
    - assets/img/exito.png
    - assets/img/spotify_logo.png
    - assets/img/driving_pin.png
    - assets/img/destination_map_marker.png
    - assets/img/runner.png
    - assets/img/default-profile.png
    - assets/img/mesomorfo.png
    - assets/img/endomorfo.png
    - assets/img/ectomorfo.png
    # Sounds
    - assets/sounds/ejercicio_start.wav
    - assets/easy.db

  fonts:
    - family: Lato
      fonts:
        - asset: fonts/Lato/Lato-Regular.ttf